# Generated by Django 5.2.5 on 2025-08-26 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_created_date_user_update_date_porfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Porfile',
            new_name='Profile',
        ),
    ]
